# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create and change to the app directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies without running prepare scripts (we will build explicitly later)
RUN npm install --ignore-scripts

# Copy source files
COPY . .

# Build the project and set executable permissions
RUN npm run build

# Expose ports if any (not specified)

# Run the MCP server
CMD [ "node", "build/index.js" ]
